apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mutilator.fullname" . }}
  labels:
    {{- include "mutilator.labels" . | nindent 4 }}
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: distributor
          app.kubernetes.io/instance: tempo
          app.kubernetes.io/name: tempo
  podSelector:
    matchLabels:
      {{- include "mutilator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
