apiVersion: v1
kind: Service
metadata:
  name: {{ include "mutilator.fullname" . }}
  labels:
    {{- include "mutilator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "mutilator.selectorLabels" . | nindent 4 }}
