{{- if not .Values.debugger.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mutilator.fullname" . }}
  labels:
    {{- include "mutilator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "mutilator.selectorLabels" . | nindent 4 }}
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mutilator.labels" . | nindent 4 }}
  name: {{ include "mutilator.fullname" . }}
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ include "mutilator.fullname" . }}
  labels:
    kubernetes.io/service-name: {{ include "mutilator.fullname" . }}
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 9443
endpoints:
  - addresses:
      - {{ .Values.debugger.host }}
    conditions:
      ready: true
{{- end }}
