apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "mutilator.fullname" . }}
  labels:
      {{- include "mutilator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "mutilator.fullname" . }}
webhooks:
  - name: {{ include "mutilator.fullname" . }}.nais.io
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: "" # "<Kubernetes CA> or <cert-manager CA>"
      service:
        name: {{ include "mutilator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.service.port }}
        path: /mutate
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["aiven.io"]
        apiVersions: ["*"]
        resources: ["redis"]
    namespaceSelector:
      matchExpressions:
        - key: team
          operator: Exists
    failurePolicy: Fail
    matchPolicy: Exact
    sideEffects: None
